spring:
  application:
    name: onboarding_assignment
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: sparta@240729
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
server:
  port: 8080

# Base64 Encode한 SecretKey
jwt:
  secret:
    key: '7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg=='
  token:
    access-expiration: 600000
    refresh-expiration: 1209600000

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8 # 요청 객체 Data Type
  default-produces-media-type: application/json;charset=UTF-8 # 응답 객체 Data Type
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
  group-configs: #문서를 페이지로 구분하는 설정
    - group: user
      paths-to-match: /api/user/**

logging:
  level:
    com.sparta.internship.onboarding_assignment: DEBUG